[package]
name = "antegen-thread-program"
description = "Antegen thread program"

version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
name = "antegen_thread_program"

[features]
anchor-debug = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []

[dependencies]
solana-cron = { workspace = true }
antegen-network-program = { workspace = true, features = ["cpi"] }
antegen-utils = { workspace = true }

anchor-lang = { workspace = true }
anchor-spl = { workspace = true }

chrono = { workspace = true }
pyth-sdk-solana = { workspace = true }
static-pubkey = { workspace = true }
version = { workspace = true }
