[workspace]
resolver = "2"
members = [
    "cli",
    "cron",
    "plugin",
    "programs/*",
    "sdk",
    "utils"
]

[profile.release]
overflow-checks = true
panic = "abort"         # Aborts on panic instead of unwinding
lto = "thin"            # Enable link-time optimization
codegen-units = 1       # Optimize for size
strip = true            # Strip symbols from binary
opt-level = 3           # Maximum optimizations

[workspace.package]
version = "1.0.0"
authors = ["Antegen Maintainers <maintainers@antegen.xyz>"]
repository = "https://github.com/wuwei-labs/antegen"
homepage = "https://antegen.xyz/"
documentation = "https://docs.antegen.xyz/"
license = "MIT"
edition = "2021"
readme = "./README.md"
keywords = ["solana"]

[workspace.dependencies]
solana-cron = { path = "cron", version = "=1.0.0" }
antegen-utils = { path = "utils", version = "=1.0.0" }
antegen-plugin-utils= { path = "plugin/utils", version = "=1.0.0" }
antegen-thread-program = { path = "programs/thread", version = "=1.0.0", features = ["no-entrypoint"] }
antegen-network-program = { path = "programs/network", version = "=1.0.0", features = ["no-entrypoint"] }

anchor-lang = { git = "https://github.com/coral-xyz/anchor", rev = "6df05aa5b5d9971041e3d25a246d935252b6e576" }
anchor-spl = { features = ["mint", "token"], git = "https://github.com/coral-xyz/anchor", rev = "6df05aa5b5d9971041e3d25a246d935252b6e576" }

actix-cors = "0.6.4"
actix-web = "4.3.1"
agave-geyser-plugin-interface = "2.1.6"
anyhow = "1.0.94"
async_once = "0.2.6"
async-trait = "0.1.83"
base64 = "0.22.1"
bincode = "1.3.3"
bs58 = "0.5.1"
bugsnag = "0.2.1"
byte-unit = "4.0.18"
bzip2 = "0.5.0"
chrono = { version = "0.4.39", default-features = false, features = ["alloc"] }
clap = { version = "4.5.23", features = ["derive"] }
dirs-next = "2.0.0"
futures = "0.3.31"
indicatif = "0.17"
lazy_static = "1.5.0"
log = "0.4"
nom = "7.1.3"
once_cell = "1.20.2"
prost = "0.12.3"
pyth-sdk-solana = "0.10"
rayon = "1.7.0"
regex = "1.7.1"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
serde = { version = "1.0.216" }
serde_json = "1.0.133"
serde_yaml = "0.9.34"
simple-error = "0.3.1"
solana-account-decoder = "=2.1.6"
solana-clap-utils = "=2.1.6"
solana-cli-config = "=2.1.6"
solana-client = "=2.1.6"
solana-logger = "2.1.6"
solana-program = "2.1.6"
solana-quic-client = "2.1.6"
solana-sdk = "=2.1.6"
solana-transaction-status = "2.1.6"
solana-zk-token-sdk = "2.1.6"
spl-associated-token-account = "6.0.0"
spl-memo = "6.0.0"
spl-token = "7.0.0"
static-pubkey = "1.0.3"
tar = "0.4"
termcolor = "1.4.1"
thiserror = "2.0.7"
toml_datetime = "=0.6.8"
tokio = "1.29.1"
version = "3.0.0"
winnow = "=0.4.1"
