[workspace]
resolver = "2"
members = [
    "cli",
    "cron",
    "plugin",
    "programs/*",
    # "relayer",
    "sdk",
    "utils"
]

[profile.release]
overflow-checks = true
panic = "abort"         # Aborts on panic instead of unwinding
lto = "thin"            # Enable link-time optimization
codegen-units = 1       # Optimize for size
strip = true            # Strip symbols from binary
opt-level = 3           # Maximum optimizations
