[package]
name = "clockwork-relayer-api"
version = "1.0.0"
edition = "2021"
description = "Clockwork relayer for webhook requests"
license = "AGPL-3.0-or-later"
homepage = "https://clockwork.wuwei.dev"
repository = "https://github.com/wuwei-labs/clockwork"
documentation = "https://clockwork.wuwei.dev/docs"
readme = "./README.md"
keywords = ["solana"]

[lib]
crate-type = ["cdylib", "lib"]
name = "clockwork_relayer_api"


[dependencies]
serde = "1.0.216"
bincode = "1.3.3"
solana-sdk = "2.1.6"
