name: Build Status

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.29.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust Stable to use with tools
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: cargo build --locked
